# Generated by Django 3.1.7 on 2021-03-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnQuran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nx', models.PositiveIntegerField(null=True)),
                ('Calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnQuran.calendrier')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnQuran.etudiant')),
            ],
        ),
    ]
