# Generated by Django 3.1.7 on 2021-03-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnQuran', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Calendrier',
            new_name='calendrier',
        ),
    ]
