# Generated by Django 3.1.7 on 2021-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnQuran', '0003_auto_20210324_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Femme', max_length=10),
        ),
    ]
