# Generated by Django 3.1.7 on 2021-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnQuran', '0005_auto_20210328_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semaine',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
